# Generated by Django 4.2.7 on 2023-11-08 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_employee_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='update_at',
        ),
        migrations.AddField(
            model_name='employee',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
